version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_schoolSystem
    environment:
      POSTGRES_DB: schoolSystem_db
      POSTGRES_USER: hadjhassinejawher
      POSTGRES_PASSWORD: changeit
    ports:
      - "5432:5432"
    volumes:
      - postgres_schoolSystem_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_schoolSystem
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_schoolSystem

volumes:
  postgres_schoolSystem_data:
